services:
  app:
    build: .
    container_name: erigo
    image: backend_erigo
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/home/python/app

    environment:
      - PYTHONPATH=/code/
    tty: true
    # env_file:
    #   - ./.env
    ports:
      - 8000:8000